# NOTE: coordinates in cell #s, choose to convert to m/cm/mm later
# Each item (11 total) in list is an obstacle. Each obstacle has vertices
# with cartesian coordinates
obstacles: [[[12.,  6.], [14.5,   3.5], [17., 5.5], [17.,  8.5],  [14., 8.]], #A
            [[24.,  6.], [26.,    3.5], [31., 7.5], [24.5, 9.5]],             #B
            [[34., 26.], [10.,    26.], [10., 12.], [34.,  12.]],             #C
            [[0.,  26.], [0.,      6.], [4.,   6.], [4.,   26.]],             #D
            [[4.,  32.], [6.,     30.], [8.,  32.]],                          #E
            [[17., 32.], [18.,    30.], [19., 32.]],                          #F
            [[0.,  36.], [0.,     32.], [29., 32.], [29.,  36.]],             #G
            [[34., 36.], [33.,    34.], [34., 32.]],                          #H
            [[6.,  44.], [2.,     43.], [2.,  39.], [6.,   38.],  [8., 41.]], #I
            [[11., 48.], [17.,    41.], [14., 48.]],                          #J
            [[30., 48.], [22.,    40.], [32., 48.]],                          #K
            [[0.,   0.], [34.,     0.]], # OUTER WALL 1
            [[34.,  0.], [34.,    48.]], # OUTER WALL 2
            [[34., 48.], [0.,     48.]], # OUTER WALL 3
            [[0.,  48.], [0.,      0.]]] # OUTER WALL 4

map_bounds: [[0.,   0.], [34.,     0.], [34., 48.], [0.,   48.]]